version: "3.7"
services:
  
  hulk:
    image: postgres:latest
    container_name: hulk
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
    volumes:
      - ./postgres/hulk:/var/lib/postgresql/hulk
  seq:
      image: datalust/seq:latest
      container_name: seq
      restart: always
      ports:
        - 5341:5341
      expose:
        - 5341
      environment:
        ACCEPT_EULA: Y
      volumes:
        - ./seq/data:/data
