version: "3.7"
services:
  identityapi:
    image: albiberto/identityserver
    container_name: identityserver
    restart: always
    ports:
      - 5000:5000
      - 5001:5001
      - 80:80
  hulk:
    image: postgres:latest
    container_name: hulk
    restart: always
    ports:
      - 5432:5432   
    environment:
      POSTGRES_USER: RobotBoy
      POSTGRES_PASSWORD: RobotBoy  # To be moved to environment file
    volumes:
      - ./postgres/hulk:/var/lib/postgresql/hulk
